### ISSUE TITLE
Bug: Socketed Rainbow Facets don't count in grail tracking 

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#19]
I've uploaded a personal stash with a oculus socketed with a rainbow facet. My expectation was, that the grail tracker would mark both items as collected, but i only tracks the oculus.
[Liselle.zip](https://github.com/youdz/d2-stash-organizer/files/6945570/Liselle.zip)

with this stash file you also can see a minor design bug, as the mouseover with item information is clipped at the top of the page:
![image](https://user-images.githubusercontent.com/1343751/128512394-33bcce63-66b0-4b3e-964b-b0a78297497f.png)

and to add still another thing: would you be open to a feature request that displays from wich socketed item a magical property stems? in this example both "5% cold dam" and "-5% monster cold res" would have a " (Rainbow Facet)" at the end of their line

**Comment by youdz** [comment]
✅  on the grail tracker bug and tooltip positioning bug (that last one will be a pain to fix).

The socketed thing might be hard to do, because both in-game and in this project mods from sockets are consolidated with the item mods themselves. So you'd need to also indicate *how much* of the magical property comes from the socket vs the item, and then if you have multiple sockets it becomes nearly impossible to display as a side note for a single property.

One option could be a side tooltip with the full detail of what is socketed. For instance be able to see the tooltip of the Rainbow Facet next to the tooltip of this item. Or as a separate tooltip in the item's description in the main view. Something like that?

**Comment by youdz** [comment]
Fixed the socketed Facets bug: they now correctly count towards the grail.

Created #24 to track the clipped tooltip.

For the feature request, let's track it in a separate issue if you think it's valuable, and we can discuss design over there. :)
