### ISSUE TITLE
Bloodletter perfection calculation is wrong

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#6]
I have several Bloodletter swords in my stash. one of them is perfect (the others vary in quality) but your organizr just shows 75% for all of them. I've attached my stash for testing purposes: [_LOD_SharedStashSave.zip](https://github.com/youdz/d2-stash-organizer/files/6869270/_LOD_SharedStashSave.zip)

![image](https://user-images.githubusercontent.com/1343751/126793035-3a5f3a0b-d5e5-4a9b-9180-a6d71b1cc238.png)
![Screenshot002](https://user-images.githubusercontent.com/1343751/126793121-f1438d05-64be-4161-8cb6-fcc0b22ffc5a.jpg)

**Comment by youdz** [comment]
I just tested, confirmed fix is part of https://github.com/youdz/d2-stash-organizer/commit/3635b10404a7c95d8708e5bb349357b0076639cb, it now looks like this when running locally with the fix:

![Screen Shot 2021-07-24 at 12 12 41](https://user-images.githubusercontent.com/4647197/126874590-d9cae7e0-c4f6-429b-b8c0-9c3c09121d7f.png)

The only problem is that I kind of want to get the UI refactor somewhat stable before releasing. Doesn't need to have a ton of new features, just working and without regressions is what I'm looking for right now. Hopefully it works this week-end, otherwise I'll go back and release the fix by itself pre-refactor.

**Comment by ChaosMarc** [comment]
No worries. Take all the time you need. I just wanted to notify you about the issue. I'm really looking forward to your next release 👍

**Comment by youdz** [comment]
Little teaser to thank you for your patience:
<img width="667" alt="Screen Shot 2021-07-24 at 17 18 39" src="https://user-images.githubusercontent.com/4647197/126881272-b5c5e0b9-5073-44d9-b3a6-fbd2e8bbb98f.png">

The display is nice, but the real value is the ability to now search "faster cast rate" and get the list of all equipments with FCR.

**Comment by ChaosMarc** [comment]
Thanks for that :) that's one of the most important things I was missing in the current version :) one suggestion though: displaying the min max values of the Stats that factor into the perfection calculation would be awesome. Just display them in brackets behind the actual value. I think some maphack had this feature and I really liked it.

**Comment by youdz** [comment]
There you go, this bug is fixed.

The UI refactor is now up, and the only real feature it added for now is searchable item mods (I guess it's a pretty big one).
But at least it sets up easier features for filtering and sorting, for the organizer and for the grail tracker.

Next, I'd really like to improve the base item display, right now this dump of whatever feels useful to display inline is... awkward.

I'm making a note of the range thing, I do agree it'd be useful.
