### ISSUE TITLE
[Not an issue with your organizer] but request for PD2 game-data version

### ISSUE THREAD

**Issue by pairofdocs** [youdz/d2-stash-organizer#7]
Hi Youdz,

I was wondering if you would be interested in having a 2nd version of your d2-stash-organizer with game-data txt files from ProjectDiablo2 (PD2)

In their recent season, the txt files are available from their `patch_d2.mpq`

I tried a bone-headed approach of just hosting the `d2-stash-organizer\src\web` directory with PD2 txts added here 
https://github.com/pairofdocs/d2-stash-organizer/tree/gh-pages

https://pairofdocs.github.io/d2-stash-organizer/

but I don't have the json data updated. and the organizer didn't load the game data

I can provide the necessary txt files and string files if you're interested

Thank you for the organizer!

(the current organizer doesn't recognize some items that pd2 added, so it failed with a shared stash)
![image](https://user-images.githubusercontent.com/76428136/126881200-bc56f852-fefb-42ac-a5f6-d9f1a426194b.png)

edit: a dungeon scarab https://github.com/pairofdocs/d2-stash-organizer/blob/gh-pages/game-data/txt/Misc.txt#L162

**Comment by pairofdocs** [comment]
Update: 

After running `npm run game-strings` and `npm run game-data`  
I included the .txt string files along with the generated jsons in the [main branch](https://github.com/pairofdocs/d2-stash-organizer/tree/main/game-data)


GH pages is now serving `/docs` from the main branch https://pairofdocs.github.io/d2-stash-organizer/  (build with `npm run build` from following the new readme 👍 )

I'm able to see some items from a shared stash file! 
[_LOD_SharedStashSave.zip](https://github.com/youdz/d2-stash-organizer/files/6873261/_LOD_SharedStashSave.zip)

But when uploading the char `.d2x` file  I wasnt seeing items

**Comment by youdz** [comment]
I'm sorry, I can barely find time to add the features I'd like on this tool for the base game, and supporting PD2 would just be too much. You're welcome to fork and set up a PD2 version of this, like you seem to be doing.

It looks like the README turned out to be helpful, I'm glad you're unblocked.

The most important warning I can give you is that Diablo 2 is full of bugs and quirks (enhanced damage computation is hardcoded in game, min damage and max damage are super complicated because of primary vs secondary damage, mods grouping has 2 configurable cases and 10 hardcoded ones, etc), so my code has plenty of special cases to cover those. If PD2 fixed some of these quirks or introduced new ones, you'll have to play whack-a-bug for a while.

**Comment by sv-v5** [comment]
Gotcha. 

I'll pull from your repo to get code and UI updates.

Looking forward to organizing loot!

**Comment by pairofdocs** [comment]
Gotcha. 

I'll pull from your repo to get code and UI updates.

Looking forward to organizing loot!
